export const DATA = {
  applist: {
    apps: [
      { appid: 216938, name: 'Pieterw test app76 ( 216938 )' },
      { appid: 660010, name: 'test2' },
      { appid: 660130, name: 'test3' },
      { appid: 578470, name: 'Break Time!' },
      { appid: 578480, name: 'Fantasy Grounds - Cyberpunk 1 (Token Pack)' },
      { appid: 578500, name: "Fantasy Grounds - Mini-Dungeon #018: Neotomas' Paradise (PFRPG)" },
      { appid: 578510, name: "Bob Saget: That's What I'm Talking About" },
      { appid: 578550, name: 'Brian Posehn: The Fartist' },
      { appid: 578560, name: 'RE:HT - War of the Human Tanks Remix Album' },
      { appid: 578570, name: 'D.L. Hughley: Clear' },
      { appid: 578580, name: 'The Golf Club 2™ - The Aristocrat: Rags to Riches' },
      { appid: 578600, name: 'A Step Into Darkness' },
      { appid: 578610, name: 'Super Pixel Smash' },
      { appid: 578630, name: 'Dave Foley: Relatively Well' },
      { appid: 578660, name: 'Kindled Cavern' },
      { appid: 578670, name: 'Conquest: Frontier Wars' },
      { appid: 578680, name: 'Frog Hop Soundtrack' },
      { appid: 578710, name: 'Shaun the Sheep' },
      { appid: 578720, name: "A Mortician's Tale" },
      { appid: 578740, name: 'SECLUSION' },
      { appid: 578760, name: 'Psyia' },
      { appid: 578770, name: 'Vector 36 - Garage Upgrade 1(x2 slot)' },
      { appid: 578800, name: 'Phantom' },
      { appid: 578820, name: 'Klaus Lee Thunder in Down Under' },
      { appid: 578830, name: 'Cavern of Time' },
      { appid: 578840, name: 'Behind You Demo' },
      { appid: 578870, name: 'MegaGlest' },
      { appid: 578880, name: 'Embrace The Fear' },
      { appid: 578890, name: "Selatria: Advent of the Dakk'rian Empire" },
      { appid: 578900, name: 'Demonheart' },
      { appid: 578920, name: 'Demon Lord' },
      { appid: 578930, name: 'LOVE 2: kuso' },
      { appid: 578940, name: 'LOVE 2: kuso (Demo)' },
      { appid: 578030, name: 'Diluvion - Special Edition Sub "Manta"' },
      { appid: 578050, name: 'Siege And Destroy' },
      { appid: 578060, name: 'Noda' },
      { appid: 578070, name: 'Corona Blossom Soundtrack' },
      { appid: 578110, name: "Eternal Destiny - Dragon's Dawn: Revenge of Tiamat" },
      { appid: 578120, name: 'Slash Arena: Online' },
      { appid: 578130, name: 'I Am Road Comic' },
      { appid: 578140, name: 'Summer Nightmare Deluxe Edition' },
      { appid: 578190, name: 'Diesel Power' },
      { appid: 578200, name: 'STANDBY – Soundtrack' },
      { appid: 578201, name: 'STANDBY – Wallpapers' },
      { appid: 578240, name: 'Ride 2 Free Bikes Pack 5' },
      { appid: 578270, name: 'World of Guns:Aircraft Guns' },
      { appid: 578290, name: 'Cladun Returns: This Is Sengoku! - Digital Soundtrack' },
      { appid: 578300, name: 'A Crashlands Story: Dev Diary' },
      { appid: 578310, name: 'BRAIN / OUT' },
      { appid: 578320, name: "Dark Parables: Jack and the Sky Kingdom Collector's Edition" },
      { appid: 578330, name: 'LEGO® City Undercover' },
      { appid: 578340, name: 'Earthfall Soundtrack' },
      { appid: 578360, name: "Dark Dimensions: City of Fog Collector's Edition" },
      { appid: 578380, name: "Diluvion - Captain's Journal" },
      { appid: 578390, name: 'Remnith' },
      { appid: 578400, name: 'The Grey Man Official Soundtrack' },
      { appid: 578410, name: 'A Crashlands Story: Dev Diary: Episode 1 - Brace for Impact' },
      {
        appid: 578411,
        name: "A Crashlands Story: Dev Diary: Episode 02 - This Ain't Gonna Kill Me",
      },
      { appid: 578412, name: "A Crashlands Story: Dev Diary: Episode 03 - Sam's Dream Game" },
      { appid: 578413, name: 'A Crashlands Story: Dev Diary: Episode 04 - Betascotch Shenanigans' },
      { appid: 578414, name: 'A Crashlands Story: Dev Diary: Episode 05 - Full Steam Ahead' },
      { appid: 578415, name: 'A Crashlands Story: Dev Diary: Episode 06 - And Then...' },
      { appid: 578420, name: 'Mars Underground' },
      { appid: 578430, name: 'Puzzle Puppers' },
      { appid: 577519, name: 'Naruto Shippuden Uncut: Hole' },
      { appid: 577520, name: 'Naruto Shippuden Uncut: Something To Fill the Hole' },
      { appid: 577521, name: 'Naruto Shippuden Uncut: Team 7 Assemble!' },
      { appid: 577522, name: 'Naruto Shippuden Uncut: The New Three-Way Deadlock' },
      { appid: 577530, name: 'Pixel Ripped 1989' },
      { appid: 577540, name: 'The Novelist: Original Score' },
      { appid: 577560, name: 'Wizard King' },
      { appid: 577570, name: 'Mage Guard' },
      { appid: 577580, name: 'Gladiator: Sword of Vengeance' },
      { appid: 577590, name: 'Fantasy Grounds - Drow (Token Pack)' },
      { appid: 577600, name: 'Diluvion - Original Soundtrack' },
      { appid: 577610, name: 'Diluvion - Digital Artbook' },
      { appid: 577620, name: 'Fantasy Grounds - Mini-Dungeon #017: Shadows of Madness (PFRPG)' },
      { appid: 577630, name: 'Dungeon Rushers - Soundtrack' },
      { appid: 577640, name: 'Space Station Loma: OPERATIONS' },
      { appid: 577650, name: 'Bad Dream: Coma Demo' },
      { appid: 577660, name: 'Titanic VR Demo' },
      { appid: 577700, name: 'THE VIDEOKID' },
      { appid: 577710, name: 'Pirates of Everseas' },
      { appid: 577720, name: 'Mike Birbiglia: What I Should Have Said Was Nothing' },
      { appid: 577730, name: 'Idle Evolution' },
      { appid: 577740, name: 'Winexy' },
      { appid: 577760, name: 'Tears of a Dragon' },
      { appid: 577780, name: 'Atramentum VR' },
      { appid: 577810, name: 'The Jackbox Party Pack 3 - Soundtrack' },
      { appid: 577850, name: 'Tiny Wheels' },
      { appid: 577890, name: 'Arena: Blood on the Sand VR' },
      { appid: 577910, name: 'Ghost Blade HD' },
      { appid: 577930, name: 'The Jackbox Party Pack 2 - Soundtrack' },
      { appid: 577980, name: 'Messiah' },
      { appid: 578000, name: 'Lucid9 - Soundtrack' },
      { appid: 578010, name: 'Australian Football Coach' },
      { appid: 578020, name: 'Diluvion - Pre-Order Sub "Derringer"' },
      { appid: 577352, name: 'Train Sim World®: BR Class 33 Loco Add-On' },
      {
        appid: 577353,
        name: 'Train Sim World®: Northern Trans-Pennine: Manchester - Leeds Route Add-On',
      },
      {
        appid: 577354,
        name: 'Train Sim World®: Long Island Rail Road: New York - Hicksville Route Add-On',
      },
      { appid: 577355, name: 'Train Sim World®: Ruhr-Sieg Nord: Hagen - Finnentrop Route Add-On' },
      { appid: 577356, name: 'Train Sim World®: West Somerset Railway Route Add-On' },
      { appid: 577358, name: 'Train Sim World®: Rapid Transit' },
      { appid: 577359, name: 'Train Sim World®: CSX GP40-2 Loco Add-On' },
      { appid: 577360, name: 'Luna and the Moonling' },
      { appid: 577370, name: 'Boost' },
      { appid: 577380, name: 'Draw The Way' },
      { appid: 577390, name: 'MAKE IT as an Artist' },
      { appid: 577400, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: PP1 Japan' },
      { appid: 577401, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: PP1 UndeadZ' },
      { appid: 577402, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: PP2 Anime' },
      { appid: 577403, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: PP2 Birds' },
      { appid: 577404, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: PP2 RADical ROACH' },
      { appid: 577405, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: PP2 Space' },
      {
        appid: 577420,
        name:
          'Double Fine Adventure: Sidequest 1 // Tim Schafer - "My Father Told Me It Would Be..."',
      },
      {
        appid: 577421,
        name: 'Double Fine Adventure: Sidequest 2 // Tim Schafer - “I’m Such a F@#$in’ Genius”',
      },
      {
        appid: 577422,
        name: 'Double Fine Adventure: Sidequest 3 // Lee Petty - "I Was a Very Pleasant Baby"',
      },
      {
        appid: 577423,
        name: 'Double Fine Adventure: Sidequest 4 // Anna Kipnis - "I Got My Dream Job"',
      },
      {
        appid: 577424,
        name: 'Double Fine Adventure: Sidequest 5 // Brandon Dillon - "There Could Possibly Be..."',
      },
      {
        appid: 577425,
        name:
          'Double Fine Adventure: Sidequest 6 // Ray Crook - "I Think it\'s OK i\'m Still Here"',
      },
      {
        appid: 577426,
        name:
          'Double Fine Adventure: Sidequest 7 // JP LeBreton - "You Don\'t Step in the Same..."',
      },
      {
        appid: 577427,
        name: 'Double Fine Adventure: Sidequest 8 // Oliver Franzke - "I Would Have Absolutely..."',
      },
      {
        appid: 577428,
        name: 'Double Fine Adventure: Sidequest 9 // Dave Gardner - "Look, the Clocks..."',
      },
      {
        appid: 577429,
        name:
          'Double Fine Adventure: Sidequest 10 // Peter McConnell - "What I Wish I Could Have..."',
      },
      {
        appid: 577430,
        name: 'Double Fine Adventure: Sidequest 11 // Khris Brown - "The Purity of Your Intent"',
      },
      {
        appid: 577431,
        name: 'Double Fine Adventure: Sidequest 12 // Camden Stoddard - "The Weight of the Sound"',
      },
      {
        appid: 577432,
        name:
          'Double Fine Adventure: Sidequest 13 // Justin Bailey - "My Seat Only Goes Back So Far"',
      },
      {
        appid: 577433,
        name: 'Double Fine Adventure: Sidequest 14 // Ben Peck - "It\'s Not Like This Every Day"',
      },
      {
        appid: 577434,
        name: 'Double Fine Adventure: Sidequest 15 // Matt Hansen - "Just Take It Seriously"',
      },
      { appid: 577440, name: "Kygo 'Carry Me' VR Experience" },
      { appid: 577450, name: 'ABZU - Official Soundtrack' },
      { appid: 577460, name: "Hunter's Grimm" },
      { appid: 577470, name: 'Last Days Of Tascaria' },
      { appid: 577480, name: 'Higurashi When They Cry Hou - Ch.5 Meakashi' },
      { appid: 577490, name: 'Minos Strategos' },
      { appid: 577510, name: "Naruto Shippuden Uncut: Kakashi's Resolve" },
      { appid: 577511, name: 'Naruto Shippuden Uncut: The Allied Shinobi Forces Jutsu' },
      { appid: 577512, name: 'Naruto Shippuden Uncut: The Ties That Bind' },
      { appid: 577513, name: 'Naruto Shippuden Uncut: Those Who Dance in the Shadows' },
      { appid: 577514, name: 'Naruto Shippuden Uncut: The All-Knowing' },
      { appid: 577515, name: 'Naruto Shippuden Uncut: Hashirama and Madara' },
      { appid: 577516, name: 'Naruto Shippuden Uncut: Era of Warring States' },
      { appid: 577517, name: 'Naruto Shippuden Uncut: My True Dream' },
      { appid: 577518, name: "Naruto Shippuden Uncut: Sasuke's Answer" },
      { appid: 576900, name: 'RAYGUN COMMANDO VR Demo' },
      { appid: 576910, name: 'Room Service' },
      { appid: 576920, name: 'Ladykiller in a Bind — Original Soundtrack' },
      { appid: 576930, name: 'Professional Farmer 2017 - Cattle & Cultivation' },
      { appid: 576940, name: 'Hunt For Gods' },
      { appid: 576950, name: 'Westard' },
      { appid: 576970, name: 'Out Of The Box Demo' },
      { appid: 576980, name: 'Western 1849 Reloaded' },
      { appid: 576990, name: "My Friend's Rubber Ducky" },
      { appid: 577000, name: 'Witchcraft' },
      { appid: 577010, name: 'Game of Aces' },
      { appid: 577020, name: 'Planes, Bullets and Vodka: Soundtrack' },
      { appid: 577030, name: 'The Tenth Line - Digital Art Book + Soundtrack' },
      { appid: 577080, name: 'A Dump in the Dark' },
      { appid: 577100, name: 'Boundel Soundtrack by James Thorley' },
      { appid: 577110, name: 'Age of Fear: Concept Art Book' },
      { appid: 577120, name: 'Archipelago: Navigable VR Comic' },
      { appid: 577130, name: 'TY the Tasmanian Tiger Soundtrack' },
      { appid: 577131, name: 'The Art of TY the Tasmanian Tiger' },
      { appid: 577150, name: 'ICEBOX: Speedgunner' },
      { appid: 577160, name: 'Skyling: Garden Defense' },
      { appid: 577180, name: 'Sin Castle' },
      { appid: 577200, name: 'Animal Lover Demo' },
      { appid: 577210, name: 'Q.U.I.R.K.' },
      { appid: 577220, name: 'Animal Lover - Original Soundtrack' },
      { appid: 577230, name: 'Three Kingdoms: The Last Warlord' },
      { appid: 577240, name: 'CogVR' },
      { appid: 577260, name: 'Gallagher: Melon Crazy' },
      { appid: 577270, name: 'VR Aquarium -雅-' },
      { appid: 577280, name: 'SCALPERS: Turtle & the Moonshine Gang' },
      { appid: 577290, name: 'Drunk or Dead' },
      { appid: 577310, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: Elephants' },
      { appid: 577311, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: Embers' },
      { appid: 577312, name: 'Jigsaw Puzzle Pack - Pixel Puzzles Ultimate: Samurai' },
      { appid: 577320, name: 'Quantic Pinball' },
      { appid: 577330, name: 'Road Fist' },
      { appid: 577350, name: 'Train Sim World®: Great Western Express' },
      {
        appid: 577351,
        name: 'Train Sim World®: Main-Spessart Bahn: Aschaffenburg - Gemünden Route Add-On',
      },
      { appid: 576470, name: 'ANIMALITY' },
      { appid: 576480, name: 'Drunken Fight Simulator' },
      { appid: 576500, name: 'Evergarden' },
      { appid: 576520, name: 'ANIMALITY - Animal Pack' },
      { appid: 576530, name: 'ANIMALITY - Animal Pack #2' },
      { appid: 576540, name: 'Brother Wings' },
      { appid: 576570, name: 'Fantasy Grounds - Heroic Characters 9 (Token Pack)' },
      { appid: 576580, name: 'Fantasy Grounds - Mini-Dungeon #016: The Halls of Hellfire (PFRPG)' },
      { appid: 576610, name: 'Galaxy Girls - Soundtrack' },
      { appid: 576611, name: 'Galaxy Girls - Wallpapers' },
      { appid: 576612, name: 'Galaxy Girls - Dakimakuras' },
      { appid: 576613, name: 'Galaxy Girls - Erica Alone in Space' },
      { appid: 576614, name: 'Galaxy Girls - Kotoha Harem' },
      { appid: 576615, name: 'Galaxy Girls - Sara Remembers' },
      { appid: 576616, name: 'Galaxy Girls - Emilia Sneaks Aboard' },
      { appid: 576617, name: 'Galaxy Girls - Poker Night' },
      { appid: 576620, name: 'VR: The Puzzle Room' },
      { appid: 576640, name: 'GUNNVR' },
      { appid: 576650, name: 'Fovos VR' },
      { appid: 576670, name: 'Sky Is Arrows' },
      { appid: 576680, name: 'The Legends of Owlia Demo' },
      { appid: 576690, name: 'King of Crowns Chess Online' },
      { appid: 576700, name: 'Hollow Halls' },
      { appid: 576720, name: 'Light And Dance VR - Music, Action, Relaxation' },
      { appid: 576730, name: 'Spirit of Maya' },
      { appid: 576740, name: 'FootRock 2' },
      { appid: 576750, name: 'Ropes And Dragons VR' },
      { appid: 576770, name: 'Low Magic Age' },
      { appid: 576790, name: 'Mesh Maker VR' },
      { appid: 576800, name: 'Final Bravely' },
      { appid: 576810, name: '2 Ninjas 1 Cup' },
      { appid: 576820, name: 'Colourise' },
      { appid: 576860, name: 'Summer Nightmare' },
      { appid: 576020, name: 'Final Theosis' },
      { appid: 576030, name: 'MHRD' },
      { appid: 576050, name: 'Other worlds India' },
      { appid: 576060, name: 'Faraway Islands' },
      { appid: 576090, name: 'Last Wings' },
      { appid: 576100, name: 'Unknown Pharaoh' },
      { appid: 576110, name: 'Where is my Brain!?' },
      { appid: 576120, name: 'Purgatory II' },
      { appid: 576130, name: 'State of Anarchy Complete: Master of Mayhem' },
      { appid: 576160, name: 'A Long Road Home' },
      { appid: 576180, name: 'Fantasy Grounds - Heroic Characters 10 (Token Pack)' },
      {
        appid: 576200,
        name: 'Fantasy Grounds - Mini-Dungeon #015: Torment at Torni Tower (PFRPG)',
      },
      { appid: 576210, name: 'Soda Drinker Pro - Soundtrack' },
      { appid: 576220, name: 'Fantasy Grounds - Scorpions of Perdition (PFRPG)' },
      { appid: 576230, name: 'Home Tech VR' },
      { appid: 576250, name: 'Fantasy Grounds - B03: It All Falls Down (5E)' },
      { appid: 576260, name: 'Winds Of Trade' },
      { appid: 576270, name: 'Fantasy Grounds - Dead Light (CoC7E)' },
      { appid: 576280, name: 'Arena Hero' },
      { appid: 576290, name: 'Huckleberry Falls' },
    ],
  },
};
